# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: ian
create_claude_symlink: false
create_gemini_symlink: false
has_ai_rules: true
has_binder: true
has_settings: true
kind: frontend-and-server
labextension_name: selenejs
project_short_description: A JupyterLab extension.
python_name: selenepy
repository: ''
test: true

