from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict

from selenepy.models import (
    ActiveCellContext,
    NotebookCellSnapshot,
    NotebookOutlineItem,
    NotebookSnapshot,
)

SuggestionContextType = Literal["local", "global"]


class SuggestedEditModel(BaseModel):
    """Single suggestion generated by the language model."""

    model_config = ConfigDict(extra="ignore")

    id: Optional[str] = None
    title: str
    description: str
    cellIndex: int
    replacementSource: str
    rationale: Optional[str] = None
    contextType: Optional[SuggestionContextType] = None


class SuggestedEditsPayload(BaseModel):
    """Top-level payload returned from the language model."""

    model_config = ConfigDict(extra="ignore")
    suggestions: list[SuggestedEditModel]


__all__ = [
    "SuggestionContextType",
    "SuggestedEditModel",
    "SuggestedEditsPayload",
    "NotebookOutlineItem",
    "NotebookCellSnapshot",
    "ActiveCellContext",
    "NotebookSnapshot",
]
