"""Pydantic models and prompts for LLM-generated notebook suggestions."""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict
from selenepy.prompts.prompts import DEFAULT_SYSTEM_PROMPT as SYSTEM_PROMPT
from selenepy.prompts.prompts import DEFAULT_GLOBAL_SYSTEM_PROMPT as GLOBAL_SYSTEM_PROMPT

SuggestionContextType = Literal["local", "global"]


class SuggestedEditModel(BaseModel):
    """Single suggestion generated by the language model."""

    model_config = ConfigDict(extra="forbid")

    id: Optional[str] = None
    title: str
    description: str
    cellIndex: int
    replacementSource: str
    rationale: Optional[str] = None
    contextType: Optional[SuggestionContextType] = None


class SuggestedEditsPayload(BaseModel):
    """Top-level payload returned from the language model."""

    model_config = ConfigDict(extra="forbid")

    suggestions: list[SuggestedEditModel]



__all__ = [
    "SuggestionContextType",
    "SuggestedEditModel",
    "SuggestedEditsPayload",
]
