"""Pydantic models and prompts for LLM-generated notebook suggestions."""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class SuggestedEditModel(BaseModel):
    """Single suggestion generated by the language model."""

    model_config = ConfigDict(extra="forbid")

    id: Optional[str] = None
    title: str
    description: str
    cellIndex: int
    replacementSource: str
    rationale: Optional[str] = None


class SuggestedEditsPayload(BaseModel):
    """Top-level payload returned from the language model."""

    model_config = ConfigDict(extra="forbid")

    suggestions: list[SuggestedEditModel]


SYSTEM_PROMPT = (
    "You review Jupyter notebooks and propose clear, actionable edits. "
    "Return only JSON matching the provided schema. "
    "Each suggestion must target one cell, cite its index, summarize the change, "
    "and provide replacement cell source text that implements the edit. "
    "Avoid repetitive or generic advice; tailor each suggestion to the supplied "
    "context and current focus."
)


__all__ = [
    "SuggestedEditModel",
    "SuggestedEditsPayload",
    "SYSTEM_PROMPT",
]
